# ---------------------------------------------------------
# 1. NAMESPACE
# ---------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
# ---------------------------------------------------------
# 2. KAFKA CLUSTER (FULL ERİŞİM - NO AUTH - EXTERNAL ACCESS)
# ---------------------------------------------------------
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: dev-kafka
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.1.0
    # replicas satırı NodePools kullanıldığı için buradan kaldırıldı.
    listeners:
      # 1. CLUSTER İÇİ ERİŞİM (Uygulamalarınız için)
      # Adres: dev-kafka-kafka-bootstrap.kafka.svc:9092
      - name: plain
        port: 9092
        type: internal
        tls: false

      # 2. CLUSTER DIŞI ERİŞİM (Sizin bilgisayarınızdan bağlanmak için)
      # Adres: <NODE-IP>:30094
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          # NodePort numarasını sabitliyoruz ki IP:30094 diyebilin
          bootstrap:
            nodePort: 30094
          brokers:
            - broker: 0
              nodePort: 30095
            - broker: 1
              nodePort: 30096
            - broker: 2
              nodePort: 30097

    # Kısıtlamasız Config
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 2
      default.replication.factor: 2
      min.insync.replicas: 2
      log.retention.hours: 168
      # ~7GB Retention
      log.retention.bytes: 7516192768
      log.segment.bytes: 1073741824
      auto.create.topics.enable: "true" # Otomatik topic oluşturma AÇIK

  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "500m"
        limits:
          memory: 1Gi
          cpu: "1000m"
    userOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: "250m"
        limits:
          memory: 512Mi
          cpu: "500m"
---
# ---------------------------------------------------------
# 3. NODE POOLS (CONTROLLER & BROKER)
# ---------------------------------------------------------
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controller
  namespace: kafka
  labels:
    strimzi.io/cluster: dev-kafka
spec:
  replicas: 2
  roles:
    - controller
  resources:
    requests:
      memory: 1Gi
      cpu: "500m"
    limits:
      memory: 2Gi
      cpu: "1000m"
  jvmOptions:
    -Xms: "1g"
    -Xmx: "1g"
    gcLoggingEnabled: true
  storage:
    type: persistent-claim
    size: 10Gi
    class: nfs-client # Burayı kendi storage class'ınızla değiştirebilirsiniz
    deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker
  namespace: kafka
  labels:
    strimzi.io/cluster: dev-kafka
spec:
  replicas: 2
  roles:
    - broker
  resources:
    requests:
      memory: 2Gi
      cpu: "1000m"
    limits:
      memory: 4Gi
      cpu: "2000m"
  jvmOptions:
    -Xms: "2g"
    -Xmx: "2g"
    gcLoggingEnabled: true
  storage:
    type: persistent-claim
    size: 20Gi
    class: nfs-client # Burayı kendi storage class'ınızla değiştirebilirsiniz
    deleteClaim: false
---
# ---------------------------------------------------------
# 4. KAFKA UI (ŞİFRESİZ - HERKES GİREBİLİR)
# ---------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "dev-kafka"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "dev-kafka-kafka-bootstrap.kafka.svc:9092"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
              value: "PLAINTEXT"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  selector:
    app: kafka-ui
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080 # Kafka UI'a Browserdan erişim portu
