apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ .Values.kafka.version | quote }}
    readinessProbe:
      initialDelaySeconds: {{ .Values.kafka.probes.readiness.initial }}
      periodSeconds: {{ .Values.kafka.probes.readiness.period }}
    livenessProbe:
      initialDelaySeconds: {{ .Values.kafka.probes.liveness.initial }}
      periodSeconds: {{ .Values.kafka.probes.liveness.period }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: {{ .Values.kafka.config.offsetsTopicReplication }}
      transaction.state.log.replication.factor: {{ .Values.kafka.config.transactionLogReplication }}
      transaction.state.log.min.isr: {{ .Values.kafka.config.minIsr }}
      log.retention.hours: {{ .Values.kafka.config.logRetentionHours }}
      log.segment.bytes: {{ .Values.kafka.config.logSegmentBytes }}
      num.partitions: {{ .Values.kafka.config.numPartitions }}
      auto.create.topics.enable: {{ .Values.kafka.config.autoCreateTopicsEnable | quote }}
      delete.topic.enable: {{ .Values.kafka.config.deleteTopicEnable | quote }}
      num.network.threads: {{ .Values.kafka.config.numNetworkThreads }}
      num.io.threads: {{ .Values.kafka.config.numIoThreads }}
      socket.send.buffer.bytes: {{ .Values.kafka.config.socketSendBufferBytes }}
      socket.receive.buffer.bytes: {{ .Values.kafka.config.socketReceiveBufferBytes }}
      socket.request.max.bytes: {{ .Values.kafka.config.socketRequestMaxBytes }}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  entityOperator:
    topicOperator:
      resources:
        {{- toYaml .Values.kafka.entityOperator.topicOperator.resources | nindent 8 }}
    userOperator:
      resources:
        {{- toYaml .Values.kafka.entityOperator.userOperator.resources | nindent 8 }}