apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.kafka.name }}-controller-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.controller.minAvailable }}
  selector:
    matchLabels:
      strimzi.io/cluster: {{ .Values.kafka.name }}
      strimzi.io/pool-name: controller
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.kafka.name }}-broker-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.broker.minAvailable }}
  selector:
    matchLabels:
      strimzi.io/cluster: {{ .Values.kafka.name }}
      strimzi.io/pool-name: broker